import Cocoa

// Clipboard history: a lightweight pasteboard watcher + on-disk store.
// Captures text / links / code (auto-labeled language) / paths / images / videos / files,
// skips password-manager (concealed/transient) clips, and de-dupes.
final class ClipStore {
    static let dir: String = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
            .appendingPathComponent("NASNotes").appendingPathComponent("clips").path
        try? FileManager.default.createDirectory(atPath: base, withIntermediateDirectories: true)
        return base
    }()
    static let jsonPath = dir + "/clips.json"
    static let maxItems = 300

    var items: [[String: Any]] = []          // newest first
    private var lastChange = NSPasteboard.general.changeCount
    private var seq = 0

    init() { load(); reclassifyExisting(); lastChange = NSPasteboard.general.changeCount }

    // MARK: persistence
    func load() {
        if let d = try? Data(contentsOf: URL(fileURLWithPath: ClipStore.jsonPath)),
           let a = (try? JSONSerialization.jsonObject(with: d)) as? [[String: Any]] { items = a }
    }

    // Re-run classification on already-stored string clips so older items pick up new categories
    // (e.g. emails/errors captured before those detectors existed).
    private func reclassifyExisting() {
        var changed = false
        for i in items.indices {
            guard let t = items[i]["text"] as? String, items[i]["path"] == nil else { continue }
            let (kind, lang) = classify(t.trimmingCharacters(in: .whitespacesAndNewlines))
            if (items[i]["kind"] as? String) != kind { items[i]["kind"] = kind; changed = true }
            if let lang = lang { items[i]["lang"] = lang } else { items[i]["lang"] = nil }
        }
        if changed { save() }
    }
    func save() {
        if let d = try? JSONSerialization.data(withJSONObject: items, options: []) {
            try? d.write(to: URL(fileURLWithPath: ClipStore.jsonPath))
        }
    }

    private func newID() -> String { seq += 1; return "\(Int(Date().timeIntervalSince1970 * 1000))-\(seq)" }

    // MARK: polling
    func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        capture(pb)
    }

    private func isPrivate(_ pb: NSPasteboard) -> Bool {
        let names = (pb.types ?? []).map { $0.rawValue }
        for n in names where n.hasPrefix("org.nspasteboard.") &&
            (n.contains("Concealed") || n.contains("Transient") || n.contains("AutoGenerated")) { return true }
        return false
    }

    private func capture(_ pb: NSPasteboard) {
        if isPrivate(pb) { return }   // don't record passwords / transient clips

        // 1) file URLs (Finder copies, video/image/other files)
        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            for u in urls { addFile(u) }
            trimAndSave(); return
        }
        // 2) image / photo data
        if let types = pb.types, types.contains(.png) || types.contains(.tiff),
           let img = NSImage(pasteboard: pb) {
            addImage(img); trimAndSave(); return
        }
        // 3) text of some kind
        if let s = pb.string(forType: .string), !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            addString(s); trimAndSave(); return
        }
    }

    private func dupeOfLatest(_ sig: String) -> Bool {
        if let first = items.first, (first["sig"] as? String) == sig { return true }
        return false
    }

    private func push(_ item: [String: Any]) { items.insert(item, at: 0) }

    // MARK: classifiers
    private func addString(_ s: String) {
        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
        let sig = "s:" + String(t.prefix(200)) + ":\(t.count)"
        if dupeOfLatest(sig) { return }
        let (kind, lang) = classify(t)
        var it: [String: Any] = ["id": newID(), "ts": Date().timeIntervalSince1970, "kind": kind,
                                 "text": String(s.prefix(50000)), "sig": sig]
        if let lang = lang { it["lang"] = lang }
        push(it)
    }

    private func addFile(_ u: URL) {
        let path = u.path, name = u.lastPathComponent
        let sig = "f:" + path
        if dupeOfLatest(sig) { return }
        let kind = fileKind(name)
        var it: [String: Any] = ["id": newID(), "ts": Date().timeIntervalSince1970, "kind": kind,
                                 "path": path, "name": name, "sig": sig]
        if kind == "image", let img = NSImage(contentsOf: u) { it["thumb"] = thumbURI(img) }
        push(it)
    }

    private func addImage(_ img: NSImage) {
        let id = newID()
        let file = ClipStore.dir + "/img-\(id).png"
        if let tiff = img.tiffRepresentation, let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            try? png.write(to: URL(fileURLWithPath: file))
        }
        let sig = "i:\(id)"
        let it: [String: Any] = ["id": id, "ts": Date().timeIntervalSince1970, "kind": "image",
                                 "path": file, "name": "Image", "thumb": thumbURI(img), "sig": sig]
        push(it)
    }

    private func fileKind(_ name: String) -> String {
        let e = (name as NSString).pathExtension.lowercased()
        let video = ["mp4","mov","mkv","avi","webm","m4v","flv","wmv","mpg","mpeg","hevc"]
        let image = ["png","jpg","jpeg","gif","heic","webp","tiff","tif","bmp","svg"]
        if video.contains(e) { return "video" }
        if image.contains(e) { return "image" }
        return "file"
    }

    // link -> email/ip/color/phone/path (single line) -> error -> code -> text
    private func classify(_ t: String) -> (String, String?) {
        if isURL(t) { return ("link", nil) }
        if !t.contains("\n") {
            if isEmail(t) { return ("email", nil) }
            if isIP(t)    { return ("ip", nil) }
            if isColor(t) { return ("color", nil) }
            if isPhone(t) { return ("phone", nil) }
            if isPath(t)  { return ("path", nil) }
        }
        if isError(t) { return ("error", nil) }
        if let lang = detectCode(t) { return ("code", lang) }
        return ("text", nil)
    }

    private func isError(_ t: String) -> Bool {
        if t.contains("Traceback (most recent call last)") { return true }
        if rx(t, "\\b\\w*(Error|Exception|Warning)\\b\\s*:") { return true }        // TypeError:, ...Warning:
        if rx(t, "\\b[\\w.\\-/]+\\.(js|ts|jsx|tsx|py|rb|go|java|swift|c|cpp|php|rs):\\d+") { return true }  // file.js:123
        if rx(t, "\\n\\s+at\\s") { return true }                                     // JS/Java stack frames
        if rx(t, "(panic:|fatal error:|Segmentation fault|Caused by:|Unhandled exception)") { return true }
        return false
    }

    private func rx(_ t: String, _ p: String) -> Bool {
        return t.range(of: p, options: [.regularExpression]) != nil
    }
    private func isEmail(_ t: String) -> Bool {
        return rx(t, "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")
    }
    private func isIP(_ t: String) -> Bool {
        if rx(t, "^(25[0-5]|2[0-4]\\d|1?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|1?\\d?\\d)){3}$") { return true }  // IPv4
        if t.contains(":"), rx(t, "^([0-9A-Fa-f]{0,4}:){2,7}[0-9A-Fa-f]{0,4}$") { return true }            // IPv6
        return false
    }
    private func isColor(_ t: String) -> Bool {
        if rx(t, "^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{4}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$") { return true }
        return rx(t, "^(rgb|rgba|hsl|hsla)\\([0-9.,%\\sA-Za-z/]+\\)$")
    }
    private func isPhone(_ t: String) -> Bool {
        guard rx(t, "^\\+?[0-9][0-9 ()\\-.]{6,20}$") else { return false }
        let digits = t.filter { $0.isNumber }.count
        return digits >= 7 && digits <= 15
    }

    private func isURL(_ t: String) -> Bool {
        guard !t.contains(" "), !t.contains("\n") else { return false }
        return t.range(of: "^(https?|ftp|ssh|mailto)://", options: [.regularExpression, .caseInsensitive]) != nil
            || t.range(of: "^www\\.[^ ]+\\.[a-z]{2,}", options: [.regularExpression, .caseInsensitive]) != nil
    }

    private func isPath(_ t: String) -> Bool {
        guard t.count < 1024 else { return false }
        if t.range(of: "^([A-Za-z]:\\\\)", options: .regularExpression) != nil { return true }   // Windows
        if t.hasPrefix("/") || t.hasPrefix("~/") || t.hasPrefix("./") || t.hasPrefix("../") {
            return t.contains("/")   // has at least one separator
        }
        return false
    }

    private func detectCode(_ t: String) -> String? {
        let lower = t.lowercased()
        func has(_ subs: [String]) -> Bool { subs.contains { t.contains($0) } }
        if t.contains("#!/bin/bash") || t.contains("#!/bin/sh") || t.contains("#!/usr/bin/env bash") { return "bash" }
        if has(["func ", "guard let", "@objc", "import Foundation", "print(\"", "-> "]) && has(["let ", "var ", "func "]) { return "swift" }
        if has(["def ", "elif ", "print("]) || (has(["import "]) && lower.contains("self")) { return "python" }
        if has(["function ", "const ", "=>", "console.log", "require(", "document.", "() {"]) { return "javascript" }
        if has(["#include", "int main", "std::", "printf("]) { return "cpp" }
        if has(["public class", "System.out", "void main"]) { return "java" }
        if has(["package main", ":= ", "fmt."]) { return "go" }
        if lower.contains("select ") && lower.contains(" from ") { return "sql" }
        if t.contains("<html") || t.contains("<!doctype") || (t.contains("</") && t.contains("<")) { return "html" }
        let jt = t.trimmingCharacters(in: .whitespacesAndNewlines)
        if (jt.hasPrefix("{") && jt.hasSuffix("}")) || (jt.hasPrefix("[") && jt.hasSuffix("]")),
           let d = jt.data(using: .utf8), (try? JSONSerialization.jsonObject(with: d)) != nil { return "json" }
        if has(["sudo ", "brew ", "git ", "cd ", "chmod ", "$(", "&&", "| "]) && t.contains("\n") == false && has(["/", "-"]) { return "bash" }
        let lines = t.split(separator: "\n")
        if lines.count >= 2 {
            let codey = t.contains("{") || t.contains(";") || t.contains("=>") ||
                t.range(of: "\\n[ \\t]{2,}\\S", options: .regularExpression) != nil
            if codey { return "code" }
        }
        if t.contains("();") || (t.contains(" = ") && t.contains(";")) { return "code" }
        return nil
    }

    private func thumbURI(_ img: NSImage, maxDim: CGFloat = 220) -> String {
        let sz = img.size
        guard sz.width > 0, sz.height > 0 else { return "" }
        let scale = min(1, maxDim / max(sz.width, sz.height))
        let w = max(1, Int(sz.width * scale)), h = max(1, Int(sz.height * scale))
        guard let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: w, pixelsHigh: h,
                                         bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true,
                                         isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0) else { return "" }
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
        img.draw(in: NSRect(x: 0, y: 0, width: w, height: h))
        NSGraphicsContext.restoreGraphicsState()
        guard let png = rep.representation(using: .png, properties: [:]) else { return "" }
        return "data:image/png;base64," + png.base64EncodedString()
    }

    private func trimAndSave() {
        if items.count > ClipStore.maxItems {
            // keep all favourites; trim oldest non-favourites beyond the cap
            var kept: [[String: Any]] = []; var nonFav = 0
            for it in items {
                let fav = (it["fav"] as? Bool) == true
                if fav || nonFav < ClipStore.maxItems { kept.append(it); if !fav { nonFav += 1 } }
                else if let p = it["path"] as? String, p.hasPrefix(ClipStore.dir) { try? FileManager.default.removeItem(atPath: p) }
            }
            items = kept
        }
        save()
    }

    // MARK: actions used by the UI bridge
    func copyBack(_ id: String) {
        guard let it = items.first(where: { ($0["id"] as? String) == id }) else { return }
        let pb = NSPasteboard.general; pb.clearContents()
        let kind = it["kind"] as? String ?? "text"
        if kind == "image", let p = it["path"] as? String, let img = NSImage(contentsOfFile: p) {
            pb.writeObjects([img])
        } else if let p = it["path"] as? String, kind == "file" || kind == "video" || (kind == "image") {
            pb.writeObjects([URL(fileURLWithPath: p) as NSURL])
        } else if let t = it["text"] as? String {
            pb.setString(t, forType: .string)
        }
        lastChange = pb.changeCount   // don't re-capture our own copy-back
    }

    func setFav(_ id: String, _ fav: Bool) {
        if let i = items.firstIndex(where: { ($0["id"] as? String) == id }) {
            if fav { items[i]["fav"] = true } else { items[i]["fav"] = nil }
            save()
        }
    }

    func delete(_ id: String) {
        if let it = items.first(where: { ($0["id"] as? String) == id }),
           let p = it["path"] as? String, p.hasPrefix(ClipStore.dir) { try? FileManager.default.removeItem(atPath: p) }
        items.removeAll { ($0["id"] as? String) == id }
        save()
    }
    func clearAll() {
        for it in items { if let p = it["path"] as? String, p.hasPrefix(ClipStore.dir) { try? FileManager.default.removeItem(atPath: p) } }
        items.removeAll(); save()
    }

    // Compact JSON for the WebView (preview text only; full text stays on disk for copy-back).
    func injectJSON() -> String {
        let out: [[String: Any]] = items.prefix(ClipStore.maxItems).map { it in
            var o: [String: Any] = ["id": it["id"] ?? "", "ts": it["ts"] ?? 0, "kind": it["kind"] ?? "text"]
            if let l = it["lang"] { o["lang"] = l }
            if (it["fav"] as? Bool) == true { o["fav"] = true }
            if let n = it["name"] { o["name"] = n }
            if let th = it["thumb"] { o["thumb"] = th }
            if let p = it["path"] as? String { o["path"] = p }
            if let t = it["text"] as? String { o["preview"] = String(t.prefix(1400)); o["len"] = t.count }
            return o
        }
        return (try? String(data: JSONSerialization.data(withJSONObject: out), encoding: .utf8)) ?? "[]"
    }
}
